sudo: required

services:
  - docker

env:
  global:
  # REGISTRY_USER
  - secure: "HhSWgkkdyGocvcNgFXC+ESfmbmkiqB8qGb7eaKPK4PtGR1AiGUP0GPopzRc0VjPX6NmAHTO048hOg0JEb2olSVKDyTvV1QZ4Tq46NG1q7dg9pvUtEPrUSUlLdk1kYSQn9PjXKjLuVs+1WmrJzl8CO+awdRMhmHHQKyolbgJL8niW1dNCpG79CXfyNvs99N3XdkLTcOeevQYkzSjuArtIMj5+yrVGRyulnfpJ8SV4FYnCmG+ezhsT9AB32ntAyVZp4ZyJDPbGXOvju5eI3w2rXCLpjrWkEoneEcJ9gaUbEzW3uStHFx6UsDqxYAeMMuZjG9F12WelOGooMGO5Gy5q+s+sTfIzuOMe5KzRSK/VAs3+SRi/AMpCciqLISqKw/MnASrB2/umfCjwPTx6inUHaNRD26XVieuao8CIQcHIzPA4b31zrXVTe1W/R1IWjgEssF7U4/ZX5m+wS1mu+cTSwli4GDEtBmrUipPwgoK3u+3I8fGsQ/AHUaL7T6WFTcjSIqFuBZR5WbU2Av5XmcsU3Raf4oPyxXqGcAXnlOhnD+s6Vkitvcza4jIZ0fMsWvrQm043SFtl+Ol0t8GedcKeE4BeyQrUSgXWBBYjnnOBbUtkn6OISBgCbp8ABDJvPt++lMCqKFja9HKCzcPO3BCwll6duLZFzvSPJiemwTJG57U="

  # REGISTRY_PASS
  - secure: "ElUzaXzr3bPhVE1GkCzXx2GsSDdaR8XxdcMd3xTrvgk2Bcixcez7eLqdiO8FhH51YaglUWr5gHd2yAVUuooPaeUOszCtDEOSXSMb2DnAaxy8Zo4J3A8SqCCvLU39irf6pWRo09e31b6/l/Kk0Ha6VPh8HqBKbmUBY1bJq8af9bokYZJd5r2vvoV4y2z8kzUT9tuhbKjkJvUb09nd3iK+GA14M09C3PfLyNkw0Z9SluUgSVU1tl90vYMEBBjNBEa//yzaD1l0bh+ji5zJDkog4vn7ZDXxYKkC4L6Kh1EccRzKNxfDoxuy4HHh40wAPnzocz3FuiCl/4xKMVaJwC5iK/9Nq+ZTxmMJUshQjtX78qUBKPthRwr6U0eZlQaLE3aMjA+ZI8660bydtsP9zRxEGloSaXZExQyv2YCxqzmd5mhKVZQXygdEuJGajPN/5thI6m6mbYdqN7rELZkK0vVRp3fTgpnfXl+rIzqI4TMR25II178PuPcULcse68BoXzK5iqVUnEmi99+ak86/KYPuFS5UpDgMkXCwYDeaGmiculYCOTQb5yqzeXm/eUj3ZqeZt5lLZr7jySVY0kXEwEI671YZSN+TJz9Dcrcxmnj58rGTAmBGd+GzMwafCGg9bLdbZ2tfthhkD4GK65o3IyFgLbjg9/8QrOg518CHg/XDI1o="

language: java
jdk: oraclejdk8

before_install:
- chmod +x scripts/install_dependencies.sh
- scripts/install_dependencies.sh

script:
- mvn clean install -PdeployToRegistry
